repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml
    -   id: check-added-large-files

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        # Ruff natively supports pydocstyle rules, no need for additional dependencies
    -   id: ruff-format

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
    -   id: mypy
        additional_dependencies: [
            "types-requests",
            "pydantic>=2.0.0",
            "sqlalchemy>=2.0.0",
            "types-aiofiles"
        ]

-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
    -   id: prettier
        types_or: [javascript, jsx, ts, tsx, json, css, markdown]

-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.0.0
    hooks:
    -   id: eslint
        files: \.(js|jsx|ts|tsx)$
        types: [file]
        additional_dependencies:
        -   eslint@8.56.0
        -   eslint-plugin-react@7.33.2
        -   typescript@5.3.3
        -   '@typescript-eslint/eslint-plugin@6.19.0'
        -   '@typescript-eslint/parser@6.19.0'
        -   'eslint-plugin-jsdoc@48.0.0'  # Add JSDoc linting

# Add a specific hook for docstring checking
-   repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0
    hooks:
    -   id: pydocstyle
        args: [--convention=google]
